name: Release

on:
  push:
    tags:
      - "*"

env:
  library: bevy_boids

jobs:
  # Publish to Crates.io
  release-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: little-core-labs/get-git-tag@v3.0.1
        id: get_version
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - name: install dependencies
        run: |
          sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Build
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu

      - name: Upload binaries to artifacts
        uses: actions/upload-artifact@v3
        with:
          path: target/x86_64-unknown-linux-gnu/release/${{ env.binary }}
          name: linux

      - name: Upload binaries to release
        if: ${{ env.add_binaries_to_github_release == 'true' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-unknown-linux-gnu/release/${{ env.binary }}
          asset_name: ${{ env.binary }}-linux-${{ steps.get_version.outputs.tag }}
          tag: ${{ github.ref }}
          overwrite: true
